//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCAREWebExperiment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iCAREAdmin
    {
        public string adminID { get; set; }
        public string adminEmail { get; set; }
        public System.DateTime dateHired { get; set; }
        public Nullable<System.DateTime> dateFinished { get; set; }
    
        public virtual iCAREUser iCAREUser { get; set; }
    }
}
