//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCAREWebExperiment.Models
{
    using System;
    using System.Collections.Generic;
    using System.Security.Cryptography;
    using System.Text;

    public partial class UserPassword
    {
        public string ID { get; set; }
        public string userName { get; set; }
        public string encryptedPassword { get; set; }
        public int passwordExpiryTime { get; set; }
        public Nullable<System.DateTime> userAccountExpiryDate { get; set; }
    
        public virtual iCAREUser iCAREUser { get; set; }

        // Encrypts the password using SHA-256
        public string EncryptPassword(string password)
        {
            using (var sha256 = SHA256.Create())
            {
                byte[] bytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(password));
                StringBuilder builder = new StringBuilder();
                foreach (byte b in bytes)
                {
                    builder.Append(b.ToString("x2"));
                }
                return builder.ToString();
            }
        }

        // Verifies that the entered password matches the stored encrypted password
        public bool ValidatePassword(string enteredPassword, string storedEncryptedPassword)
        {
            string hashedEnteredPassword = EncryptPassword(enteredPassword);
            return hashedEnteredPassword == storedEncryptedPassword;
        }
    }
}
